apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: techchallenge
  labels:
    app: techchallenge
    component: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: consumer
  template:
    metadata:
      labels:
        app: techchallenge
        component: consumer
    spec:
      containers:
        - name: consumer
          image: jcoaio/techchallenge-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 1234
