name: techchallenge

services:
  api:
    image: jcoaio/techchallenge-api:latest
    ports:
      - "8080:8080"
    networks:
      - technetwork
    depends_on:
      - consumer

  consumer:
    image: jcoaio/techchallenge-consumer:latest
    ports:
      - "8082:8080"
    networks:
      - technetwork
    depends_on:
      - bus

  bus:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: techchallenge
      RABBITMQ_DEFAULT_PASS: 123456Tech
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25676:25676"
    networks:
      - technetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456Tech
      MYSQL_DATABASE: techchallenge
      MYSQL_USER: sis_techchallenge
      MYSQL_PASSWORD: 123456Tech
    ports:
      - "3306:3306"
    networks:
      - technetwork
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - technetwork
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - technetwork
    volumes:
      - grafana_data:/var/lib/grafana


networks:
  technetwork:
    driver: bridge

volumes:
  db_data:
  prometheus_data:
  grafana_data:
