apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  namespace: techchallenge
  labels:
    app: techchallenge
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techchallenge
      component: api
  template:
    metadata:
      labels:
        app: techchallenge
        component: api
    spec:
      containers:
        - name: api
          image: jcoaio/techchallenge-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: database-connectionString
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: database-connectionString
            - name: bus-server
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: bus-server
            - name: bus-user
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: bus-user
            - name: bus-password
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: bus-password
